# Generated by Django 3.2.9 on 2021-12-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchaseorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
